apiVersion: v1
kind: Service
metadata:
  name: marketdata-ingestor
  labels:
    app: marketdata-ingestor
spec:
  type: ClusterIP
  selector:
    app: marketdata-ingestor
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080

