// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingApp.MarketAnalytics.Service.Infrastructure.Persistence;

#nullable disable

namespace TradingApp.MarketAnalytics.Service.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260224222616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingApp.MarketAnalytics.Service.Domain.AggregatedMarketAnalyticsEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric(18,8)");

                    b.Property<int>("TradesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Symbol", "WindowStartUtc");

                    b.ToTable("aggregated_market_analytics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
