// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingApp.MarketAnalytics.Service.Infrastructure.Persistence;

#nullable disable

namespace TradingApp.MarketAnalytics.Service.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260224225858_SnakeCaseColumns")]
    partial class SnakeCaseColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingApp.MarketAnalytics.Service.Domain.AggregatedMarketAnalyticsEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("last_price");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("low_price");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("open_price");

                    b.Property<int>("TradesCount")
                        .HasColumnType("integer")
                        .HasColumnName("trades_count");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("volume");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end_utc");

                    b.HasKey("Symbol", "WindowStartUtc")
                        .HasName("pk_aggregated_market_analytics");

                    b.ToTable("aggregated_market_analytics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
