apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              valueFrom:
                configMapKeyRef:
                  name: elastic-config
                  key: discovery.type
            - name: xpack.security.enabled
              valueFrom:
                configMapKeyRef:
                  name: elastic-config
                  key: xpack.security.enabled
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: elastic-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elastic-data
          emptyDir: {}

