apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-indexer-worker-config
data:
  KAFKA__ENABLED: "true"
  KAFKA__BOOTSTRAPSERVERS: "kafka:9092"
  KAFKA__CONSUMER__TOPIC: "aggregated-market-analytics"
  KAFKA__CONSUMER__GROUPID: "analytics-indexer-worker"
  KAFKA__CONSUMER__AUTOOFFSETRESET: "Earliest"
  KAFKA__CONSUMER__ENABLEAUTOCOMMIT: "true"
  ELASTIC__ENDPOINT: "http://elastic:9200"
  ELASTIC__INDEXPREFIX: "analytics-index"

