apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-indexer-worker-config
data:
  KAFKA__ENABLED: "true"
  KAFKA__BOOTSTRAPSERVERS: "kafka:9092"
  KAFKA__CONSUMER__TOPIC: "aggregated-market-analytics"
  KAFKA__CONSUMER__GROUPID: "analytics-indexer-worker"
  KAFKA__CONSUMER__AUTOOFFSETRESET: "Earliest"
  KAFKA__CONSUMER__ENABLEAUTOCOMMIT: "true"
  INDEXER__BOOTSTRAPSERVERS: "kafka:9092"
  INDEXER__TOPIC: "aggregated-market-analytics"
  INDEXER__GROUPID: "analytics-indexer-worker"
  INDEXER__INDEXPREFIX: "analytics-index"
  ELASTIC__URI: "http://elastic:9200"
  LOGGING__ELASTICSEARCH__URL: "http://elastic:9200"

