apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-indexer-worker
  labels:
    app: analytics-indexer-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-indexer-worker
  template:
    metadata:
      labels:
        app: analytics-indexer-worker
    spec:
      containers:
        - name: analytics-indexer-worker
          image: trading/analyticsindexer-worker:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: INDEXER__BOOTSTRAPSERVERS
              valueFrom:
                configMapKeyRef:
                  name: analytics-indexer-worker-config
                  key: INDEXER__BOOTSTRAPSERVERS
            - name: INDEXER__TOPIC
              valueFrom:
                configMapKeyRef:
                  name: analytics-indexer-worker-config
                  key: INDEXER__TOPIC
            - name: INDEXER__GROUPID
              valueFrom:
                configMapKeyRef:
                  name: analytics-indexer-worker-config
                  key: INDEXER__GROUPID
            - name: INDEXER__INDEXPREFIX
              valueFrom:
                configMapKeyRef:
                  name: analytics-indexer-worker-config
                  key: INDEXER__INDEXPREFIX
            - name: ELASTIC__URI
              valueFrom:
                configMapKeyRef:
                  name: analytics-indexer-worker-config
                  key: ELASTIC__URI
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

