<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <AssemblyName>TradingApp.MarketAnalytics.Service</AssemblyName>
    <RootNamespace>TradingApp.MarketAnalytics.Service</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\TradingApp.Contracts\TradingApp.Contracts.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\TradingApp.Kafka\TradingApp.Kafka.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\TradingApp.Elastic\TradingApp.Elastic.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.3.0" />
    <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="10.0.0" />
  </ItemGroup>
</Project>

